name: Linux Github Action CI

permissions:
  contents: read

on:
  pull_request:
    branches:
      - SYCLomatic
    types: [opened, synchronize, reopened, ready_for_review]

env:
  BUILD_CONCURRENCY: 2
  MACOS_BUILD_CONCURRENCY: 3
  TEST_TIMEOUT: 3600

jobs:

  linux-test:
    name: linux-test-${{ matrix.test_suite }}-cpu
    runs-on: lin_ci_test
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        include:
          - test_suite: user_guide_samples
          - test_suite: regressions
          - test_suite: samples
          - test_suite: help_function
          - test_suite: features
          - test_suite: api_coverage
          - test_suite: behavior_tests
          - test_suite: applications
    steps:
      - name: Process ENV
        id: process_env
        run: |
          for mask_value in $(jq -r '.[]' $GITHUB_WORKSPACE/../../../../mask_env_values.json); do 
              echo "add mask for $mask_value"; 
              echo "::add-mask::$mask_value"; 
          done

      - name: Cleanup Workspace
        shell: bash
        run: |
          rm -rf ${{ github.workspace }}/*
      - uses: actions/checkout@v2
        with:
          path: c2s_test_repo

      - name: Checkout Source Repo
        #uses: actions/checkout@v2
        #with:
        #  repository: 
        #  path: c2s_test_repo
        env:
          FACELESS_TOKEN: ${{ secrets.GH_CI_NSTESTER_TOKEN }}
        run: |
          git clone https://$FACELESS_TOKEN@github.com/oneapi-src/SYCLomatic.git c2s.src -b SYCLomatic
          cd c2s.src
          DATE_YESTERDAY=$(git rev-list -1 --before=`date --utc -d yesterday +"%Y-%m-%d"` SYCLomatic)
          git reset ${DATE_YESTERDAY} --hard

      - name: Get_Latest_Nightly
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 10
          retry_wait_seconds: 60
          shell: bash
          command: |
            ARCHIVE_PATH=$(cat $GITHUB_WORKSPACE/../../../../GH_CI_LIN_ARCHIVE_FOLDER.txt)
            find $ARCHIVE_PATH -maxdepth 1 -type d -name "*_*0000" -print | sort -r | head -1 |xargs -i cp -r "{}/build/linux_prod/" ./
            mv linux_prod c2s.obj

      - name: Prepare Env
        timeout-minutes: 60
        uses: ./c2s.src/devops/actions/prepare_env_lin
        with:
          c2s_obj_dir: "c2s.obj"
        
      - name: Run testing option_cpu
        timeout-minutes: 180
        shell: bash
        run: |
          cd c2s_test_repo
          time python run_test.py --suite ${{ matrix.test_suite }} --option option_cpu
          echo $PWD

      - name: Run testing option_usmnone_cpu
        if: success() || failure()
        timeout-minutes: 180
        shell: bash
        run: |
          cd c2s_test_repo
          time python run_test.py --suite ${{ matrix.test_suite }} --option option_usmnone_cpu
          echo $PWD

