name: Windows Github Action CI

permissions:
  contents: read

on:
  pull_request:
    branches:
      - SYCLomatic
    types: [opened, synchronize, reopened, ready_for_review]

env:
  BUILD_CONCURRENCY: 2
  MACOS_BUILD_CONCURRENCY: 3
  TEST_TIMEOUT: 3600

jobs:
  windows-test:
    name: windows-test-${{ matrix.test_suite }}-cpu
    if: github.event.pull_request.draft == false
    runs-on: win_ci_test

    strategy:
      fail-fast: false
      matrix:
        include:
          - test_suite: user_guide_samples
          - test_suite: regressions
          - test_suite: samples
          - test_suite: api_coverage
          - test_suite: behavior_tests
    steps:
      - uses: actions/checkout@v2
        with:
          path: c2s_test_repo

      - name: Cleanup Workspace
        run: |
          if exist c2s.obj rd /s /q c2s.obj
          if exist c2s.src rd /s /q c2s.src
          if exist c2s_obj.7z del /s /q c2s_obj.7z
          if not exist "P:\" (net use P: "\\scssgfiler01.sc.intel.com\cmplrarch" /Y)
        shell: cmd

      - name: Get_Latest_Nightly
        shell: bash
        run: |
          ARCHIVE_PATH=$(cat $GITHUB_WORKSPACE/../../../GH_CI_WIN_ARCHIVE_FOLDER.txt)
          cp -r $ARCHIVE_PATH/latest/build/win_prod ./
          mv win_prod c2s.obj

      - name: Checkout Source Repo
        shell: bash
        env:
          FACELESS_TOKEN: ${{ secrets.GH_CI_NSTESTER_TOKEN }}
        run: |
          git clone https://$FACELESS_TOKEN@github.com/oneapi-src/SYCLomatic.git c2s.src -b SYCLomatic
          cd c2s.src
          DATE_YESTERDAY=$(git rev-list -1 --before=`date --utc -d yesterday +"%Y-%m-%d"` SYCLomatic)
          git reset ${DATE_YESTERDAY} --hard

      - name: Process ENV
        id: process_env
        run: |
          for mask_value in $(C:/jq-win64.exe -r ".[]" $GITHUB_WORKSPACE/../../../mask_env_values.json); do
              echo "add mask for $mask_value";
              echo "::add-mask::$mask_value";
          done
        shell: bash

      - name: Prepare Env
        timeout-minutes: 60
        uses: ./c2s.src/devops/actions/prepare_env_win

      - name: Run testing option_cpu
        timeout-minutes: 180
        shell: bash
        run: |
          cd c2s_test_repo
          python run_test.py --suite ${{ matrix.test_suite }} --option option_cpu
          echo $PWD

      - name: Run testing option_usmnone_cpu
        if: success() || failure()
        timeout-minutes: 180
        shell: bash
        run: |
          cd c2s_test_repo
          python run_test.py --suite ${{ matrix.test_suite }} --option option_usmnone_cpu
          echo $PWD

